Use new significance algorithm by default
rust-lang/rustc-perf pull request #1047
Opened 2021-10-03 01:15 UTC by Mark-Simulacrum

This currently just completely removes the old algorithm (at least where it was if-gated). I think we could allow switching back, but I've not really seen a use case for that (you can always disable filtering by significance in the UI).

2021-10-04 15:21 UTC, rylev requested changes
I think we should keep the old algorithm around for a little bit. If we happen to see interesting or surprising results, it will be good to check against the old algorithm

2021-10-04 15:29 UTC, Mark-Simulacrum commented
Alright, replaced with just swapping the default, I believe.

2021-10-04 20:33 UTC, rylev requested changes
Can you also change the default [here](https://github.com/rust-lang/rustc-perf/blob/265aa9447e37a935960aaa22b6f6f2fdd685ca9e/site/src/comparison.rs#L356)?

2021-10-05 01:19 UTC, Mark-Simulacrum commented
Yes, yes. Sorry for being so bad at identifying these places :)

2021-10-05 07:29 UTC, merged