Add `ripgrep-13.0.0` as a new benchmark
rust-lang/rustc-perf pull request #1224
Opened 2022-03-21 10:59 UTC by Kobzol

It's slower to compile than the old `ripgrep`, although it seems to me that most of the time was spent by compiling dependencies (`ripgrep` has only 5k lines of code).
```
ripgrep check 6.8
ripgrep debug 10.07
ripgrep release 20.97

ripgrep-13.0.0 check 12.38
ripgrep-13.0.0 debug 18.08
ripgrep-13.0.0 release 25.31
```

2022-03-21 19:31 UTC, nnethercote commented on collector/benchmarks/README.md
> +- **ripgrep-13.0.0**: A line-oriented search tool. A widely-used utility.
Strictly speaking, you should leave the old `ripgrep` there until it's removed in a later PR.

2022-03-21 19:34 UTC, nnethercote commented on collector/benchmarks/ripgrep/Cargo.lock
> +version = 3
This file shouldn't be changed.

2022-03-21 19:39 UTC, nnethercote requested changes
Thank you for doing this. Mostly looks good, just a couple of minor things that need fixing.

2022-03-21 19:59 UTC, bjorn3 commented
Isn't most of the logic of ripgrep in the grep library crate?

2022-03-21 20:28 UTC, Kobzol commented
It is, I suppose that ripgrep is really mostly a thin wrapper over `grep` + `regex`.

2022-03-21 21:59 UTC, nnethercote commented
I compared `ripgrep` and `ripgrep-13.0.0`, just the time for the final crate:

Benchmark & Profile | Scenario | % Change | Significance Factor? | [object HTMLSpanElement] | [object HTMLSpanElement]
-- | -- | -- | -- | -- | --
helloworld check | full | 0.00% | - | 0.16 | 0.16
helloworld opt | full | 0.00% | - | 0.22 | 0.22
helloworld debug | full | 0.00% | - | 0.23 | 0.23
ripgrep check | full | 0.00% | - | 0.53 | 0.53
ripgrep debug | full | 0.00% | - | 1.38 | 1.38
ripgrep opt | full | 0.00% | - | 3.67 | 3.67
ripgrep-13.0.0 check | full | 0.00% | - | 0.48 | 0.48
ripgrep-13.0.0 debug | full | 0.00% | - | 1.75 | 1.75
ripgrep-13.0.0 opt | full | 0.00% | - | 4.13 | 4.13

It's not that different. So I think it's still a reasonable benchmark to have.

@Kobzol I had to add a `"touch_file": "crates/core/main.rs"` to `ripgrep-13.0.0/perf-config.json` to get the `bench_local` run to work. Have you run the new benchmark under `collector`?

2022-03-22 14:50 UTC, Kobzol commented on collector/benchmarks/ripgrep/Cargo.lock
> +version = 3
Oops, good catch, thanks.

2022-03-22 14:51 UTC, Kobzol commented
@nnethercote I ran it under `bench_local` and it did work. The `perf-config.json` should already contain `"touch_file": "crates/core/main.rs"` :thinking:

2022-03-22 23:17 UTC, nnethercote approved these changes
The changes are good, though I'm worried about the weirdness with the commit message not looking normal.

2022-03-23 10:01 UTC, merged