Update database documentation
rust-lang/rustc-perf pull request #1607
Opened 2023-06-03 16:53 UTC by Kobzol

This PR updates the documentation of the DB to:
1) Fill in gaps
2) Unify the terminology better with the existing glossary
3) Add the notion of runtime benchmarks

2023-06-20 05:29 UTC, nnethercote requested changes

2023-06-20 13:07 UTC, Kobzol commented on docs/glossary.md
>  * **scenario**: The scenario under which a user is compiling their code. Currently, this is the incremental cache state and an optional change in the source since last compilation (e.g., full increme
Nice! Added it in.

2023-06-21 05:09 UTC, nnethercote approved these changes

2023-06-21 05:09 UTC, nnethercote commented on database/schema.md
> +Describes the parametrization of a runtime benchmark. Contains a unique combination
```suggestion
Describes the parameterization of a runtime benchmark. Contains a unique combination
```
Here and in some other places.

2023-06-21 05:09 UTC, nnethercote commented on docs/glossary.md
> +* **artifact**: a specific rustc binary labeled by some identifier tag (usually a commit sha or some sort of human readable id like "1.51.0" or "test").
I use "suite" to refer to all the benchmarks, i.e. primary + secondary.

2023-06-21 07:33 UTC, merged