[Draft] Add unit test for `fill_libraries`
rust-lang/rustc-perf pull request #1846
Opened 2024-03-11 07:29 UTC by chengr4

I was trying to add unit tests for `fill_libraries` of `ToolchainComponents`, but it seems like `fill_libraries` can't find the path created by `tempfile`, causing `components.lib_rustc` to be `None`. 

```rust
let dir = tempfile::tempdir().unwrap();  // create mock dir
let file_path = dir.path().join("librustc_driver.so"); // create mock file
let _file = File::create(&file_path).unwrap();
```

The three lines can create a temp file at `/var/folders/c_/cz61mkg50r9_z4lyndqjmnlw0000gn/T/.tmpR7l2bp/librustc_driver.so`

I hope to borrow someone's insights about this to find a solution. I have spent some hours testing it and could not understand why. 😓

## Current Result

```
thread 'toolchain::tests::test_fill_libraries' panicked at collector/src/toolchain.rs:616:9:
assertion `left == right` failed
 left: None
 right: Some("librustc_driver.so")
```

---

> BTW, I think it is better to figure out this with PR (find code base easier), If I should put this in the "issue", please let me know.

2024-03-11 09:20 UTC, Kobzol commented
Hi! Note that `fill_libraries` takes a path to a directory as input, not a path to the library (the library path is what the function computes). So you should put `dir.path()` to the function. Also, you should drop the opened `_file`, to make sure that it will be actually created on disk by the time you call `fill_libraries`.

2024-03-12 05:07 UTC, chengr4 commented
> Hi! Note that `fill_libraries` takes a path to a directory as input, not a path to the library (the library path is what the function computes). So you should put `dir.path()` to the function. Also, you should drop the opened `_file`, to make sure that it will be actually created on disk by the time you call `fill_libraries`.

Thank you so much !@Kobzol. Your magical "prompt" saves my time 🥹.

Firstly, could you please provide me with two specific filenames related to the old and new versions of `libLLVM.so`? I would like to add them to the test case. 

Additionally, I would like to ask for your assistance in confirming that my **"naming"** is OK.

And If you notice any other issues elsewhere, please let me know 🙏.

2024-03-12 06:43 UTC, Kobzol commented
> Firstly, could you please provide me with two specific filenames related to the old and new versions of libLLVM.so? I would like to add them to the test case.

Old LLVM can be e.g. `libLLVM-17-rust-1.76.0-stable.so` (you can check `$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib` to find an example LLVM library path).
New LLVM can be e.g. `libLLVM.so.18.1-rust-1.78.0-nightly`.

Naming is fine. I prefer not to prefix tests with `test_`.

2024-03-13 04:49 UTC, chengr4 commented
@Kobzol 
I add the test case for LLVM in random way. 
Please check it out whether it is appropriate.

---

BTW,

my `$HOME/.rustup/toolchains/stable-aarch64-apple-darwin/lib` shows
```
librustc-stable_rt.asan.dylib          librustc_driver-1230441069d3e3cb.dylib
librustc-stable_rt.lsan.dylib          libstd-b0083070c892a1db.dylib
librustc-stable_rt.tsan.dylib          libtest-597563d0b411a8e9.dylib
```
it looks like aarch MAC is using an another extension. I have no idea whether this will be a problem.

2024-03-13 06:36 UTC, Kobzol commented
Well, since the collector doesn't support macOS, it is not a problem currently :D

2024-03-13 18:25 UTC, Kobzol commented on collector/src/toolchain.rs
> +        let mut rng = rand::thread_rng();
This seems to be unnecessarily complicated and over-engineered :sweat_smile: And also having random/nondeterministic tests is not a good idea, when it's not needed.

Could you please simplify the test to this:
1) Create a directory with LLVM, rustc and libstd `.so` files
2) Call `fill_libraries` on the directory
3) Assert that the paths of the component attributes equals the created paths.

And then you can create two of these tests, one for the old and one for the new LLVM format.

2024-03-15 08:25 UTC, Kobzol requested changes
Thanks! Now it's much cleaner. A small cleanup and it's ready to go :)

2024-03-15 08:25 UTC, Kobzol commented on collector/src/toolchain.rs
> +        let _ = components.fill_libraries(temp_dir.path());
```suggestion
        components.fill_libraries(temp_dir.path()).unwrap();
```
to avoid ignoring a potential error. (same in the other test).

2024-03-15 08:25 UTC, Kobzol commented on collector/src/toolchain.rs
> +        let _ = temp_dir.close();
```suggestion
```
This is not needed, it will be destroyed automatically

2024-03-15 08:25 UTC, Kobzol commented on collector/src/toolchain.rs
> +        drop(lib_file);
```suggestion
```
Since this is now in a function, this is no longer needed, the file will be dropped (and closed) when the function call ends.

2024-03-16 08:51 UTC, Kobzol commented
Thank you, now it looks good :) Before merging, it would be nice if you squashed the commits - 10 commits is quite a lot for two added tests. You can do it e.g. like this:
```bash
$ git fetch origin master
$ git checkout unit-test
$ git reset --soft $(git merge-base HEAD master)
$ git commit -m"..." # Write a commit message
$ git push --force-with-lease
```

2024-03-16 21:55 UTC, chengr4 commented
made it!

2024-03-16 21:56 UTC, Kobzol approved these changes
Thanks!

2024-03-16 21:58 UTC, merged